
* Tile
  The tile is the basic unit.
  active: a boolean representing if the tile is to be drawn or not.
  position: the 2D integer coordinates of its position on the canvas.
  color: a vec4 representing its current color.
  state: an enum for specifying custom state.
  
  Tiles are stored in a buffer sized to be gridWidth * gridHeight
* GetTile()
  GetTile(int x, int y)
  GetTile(vec2i pos)

  Returns a pointer to the tile at the specified position.
  
* GetTileBlock()
* ComputeGridSize()
  This reallocates the buffer of tiles.

  Since the dimensions change the tiles are completely wiped, so any state stored on the tiles is lost, and any pointers to tiles are invalidated.
  
* DrawText(position, size, color, string)
  This will start drawing text at the position you specified, moving right to left.
  The size is a scalar which multiplies the the font's default pixel size. For instance if the font's height in pixels is 64, then drawing with a size of 8 will make the height of the rendered glyph 256.
  
